-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying NOT NULL,
    password character varying NOT NULL,
    create_date date NOT NULL,
    update_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    employee_id integer,
    first_name character varying,
    last_name character varying,
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.jobseekers
(
    jobskeer_id integer,
    first_name character varying,
    last_name character varying,
    identity_id character varying,
    date_of_year integer,
    PRIMARY KEY (jobskeer_id)
);

CREATE TABLE public.job_positions
(
    id integer,
    name character varying,
    is_active boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    employer_id integer,
    name character varying,
    web_site character varying,
    phone_number character varying,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.verification_jobskeers
(
    id integer NOT NULL,
    jobskeer_id integer NOT NULL,
    is_verified boolean NOT NULL,
    verify_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification_employers
(
    id integer NOT NULL,
    employer_id integer NOT NULL,
    employee_id integer NOT NULL,
    is_verified boolean NOT NULL,
    verification_date date NOT NULL,
    is_confirm boolean NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.verification_jobskeers
    ADD FOREIGN KEY (jobskeer_id)
    REFERENCES public.jobseekers (jobskeer_id)
    NOT VALID;


ALTER TABLE public.verification_employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (employer_id)
    NOT VALID;


ALTER TABLE public.verification_employers
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY (jobskeer_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.users (id)
    NOT VALID;

END;